server:
  port: 8081

spring:
  application:
    name: spring-api-performance
  jackson:
    property-naming-strategy: SNAKE_CASE
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  r2dbc:
    host: postgres-db
    database: spring-api-performance-test
    username: postgres
    password: password
    maximum-pool-size: ${db_maximum_pool_size:100}
    initial-pool-size: ${db_minimum_idle:100}
  flyway:
    enabled: true
    validate-on-migrate: true
    url: jdbc:postgresql://postgres-db:5432/spring-api-performance-test
    password: password
    user: postgres

clients:
  seller: http://spring-reactive-mock:9090
  risk-analysis: http://spring-reactive-mock:9090
  payment-gateway: http://spring-reactive-mock:9090

feign:
  client:
    config:
      default:
        connectTimeout: 20000
        readTimeout: 20000

logging:
  level:
    org.springframework.jdbc: DEBUG
    com.zaxxer.hikari: TRACE
    com.zaxxer.hikari.HikariPool: DEBUG
    com.zaxxer.hikari.HikariConfig: DEBUG
    org.springframework.boot.autoconfigure.jdbc.DataSourceProperties: DEBUG
